<a href="https://colab.research.google.com/github/LuisaRodriguezC/Clase-1/blob/main/03_Data_Structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. what is a DS?**

A DS is an object that let us store moer than one value.

Formally, a DS is **squence** of values which can be located with an index.

# **2. Linear Algebra**


## 2.1 What is Numpy?

Numpy (Numerical python) is a collection of functions and methods.


In [3]:
# Install the library

import numpy as np 

## 2.2. Numpy arrays - vectors and matrices 

*Example 1 - Colum vector*

In [4]:
a = np.array([[1],[2],[3]])
print(a)

[[1]
 [2]
 [3]]


## *Example 2* - Row Vector

In [5]:
b = np.array([[4,5,6]])
print(b)
print(b.shape)

[[4 5 6]]
(1, 3)


## *Example 3 - Matrix*

In [ ]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# nice trick 

nr, nc = M.shape 

# 2.3. Sciling 

The access one sveral elements of the object.

In [ ]:
# Extract the first element

## Column vector 
print(a[0,0])

## Row vector 
print(b[0,0])

## Matrix
print(M,[0,0])


1
2


In [ ]:
# Extract the last element

## Column vector 
print(a[-1,0])

## Row vector 
print(b[0,-1])

## Matrix
print(M,[-1,-1])

In [ ]:
# Extract a subset

## Column vector 
print(a[0:2])

## Row vector 
print(b[0,0:2])

## Matrix
print(M,[0:2,0:2])



[[1]
 [2]]


# 2.4. Methods

In [ ]:
# ZEROS

z1 = np.zeros(4)
print(z1)

z2 = np.zeros((3,2))
print(z2)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# ONES

o1 = np.ones(4)
print(o1)

o2 = np.ones((3,2))
print(o2)

o2*5

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[5., 5.],
       [5., 5.],
       [5., 5.]])

**ANOTHER CREATION OPTIONS**

In [ ]:
# Full 

f = np.full((3,2),3.55565)
print(f)

[[3.55565 3.55565]
 [3.55565 3.55565]
 [3.55565 3.55565]]


In [ ]:
# Linear sequence

np.arange(6)
np.arange(23,33)
np.arange(23,33,0.5)

array([23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5])

In [ ]:
# Linear space 

np.linspace(15,90,6)

array([15., 30., 45., 60., 75., 90.])

## 2.5. Random Numbers


In [ ]:
# A single Value - between 0 y 1

np.random.seed(1234) 
np.random.rand()

0.1915194503788923

In [ ]:
# Example - toss a coin 

if np.random.rand() < 0.5:
   print('head')
else:
     print('tails')

tails


In [ ]:
# you win if you get two heads
if np.random.rand() < 0.25:
   print('you win!')
else:
     print('you lose!')

you lose!


In [ ]:
# Two heads in a row

ft = np.random.rand()
if ft < 0.5:
   print('the first toss was head')
else:
     print('the first toss was tails')

st = np.random.rand()
if st < 0.5:
   print('the second toss was head')
else:
     print('the second toss was tails')

if ft < 0.5 and st < 0.5:
  print('you win!')
else:
  print('you lose!')


the first toss was head
the second toss was head
you win!
